version: "v0.9.1"
model_name: "flux-dev"
device: "cuda"
offload: true
aggressive_offload: false
fp8: true
onnx_provider: "gpu"
# If you have a pre-trained model file for PuLID:
pretrained_model: null
t5_max_length: 128
num_steps: 28
guidance: 3.5
start_step: 0
id_weight: 0.1
height: 1024
width: 1024
true_cfg: 3.5
timestep_to_start_cfg: 1
seed: 42
# neg_prompt: "bad quality, worst quality, text, signature, watermark"
neg_prompt: ""
use_ipa: true
gamma: 0.5
eta: 0.7
s: 0
tau: 5